### ISSUE TITLE
Fix stats peer review badge

### ISSUE THREAD

**Issue by mpadge** [joelnitta/canaper#26]
Hi @joelnitta, this is an issue for me to address. I noticed that this package does not have a stats peer review badge. This was because the badge was assigned via a code glitch at the time (just above [this review comment](https://github.com/ropensci/software-review/issues/475#issuecomment-1247317671)) to a silly version that doesn't really exist. I've just manually put the proper label on your review issue, in response to which our [badge server](https://github.com/ropensci-org/badges) should automatically update your badge next time it builds (at least daily).

In case I forget to check: Can you please confirm that badge updates here, and close this if so? Thanks!

**Comment by joelnitta** [comment]
Thanks @mpadge 

It looks like it:

<img width="613" alt="canaper" src="https://github.com/ropensci/canaper/assets/13459362/ff7aa734-1112-4f74-8e87-06841fad5e97">

So I will close this now.

**Comment by mpadge** [comment]
Nice, thanks Joel.
